use QuizzApp

insert into Tema(nmtema) values ('Ciencia e Tecnologia')
insert into Tema (nmtema) values ('Cultura Geral')
insert into Tema (nmtema) values ('Entretenimento')
insert into Tema (nmtema) values ('Esportes')
insert into Tema (nmtema) values ('Arte e Literatura')
insert into Tema (nmtema) values ('Atualidade')
insert into Tema (nmtema) values ('Gastronomia')
insert into Tema (nmtema) values ('Meio Ambiente')
insert into Tema (nmtema) values ('Linguas e Culturas')
insert into Tema (nmtema) values ('Psicologia e Bem-Estar')

select*from Tema

insert into Topico(nmtopico, temaid) values ('Avanços cientifícos recentes','1')
insert into Topico(nmtopico, temaid) values ('Invenções históricas','1')
insert into Topico(nmtopico, temaid) values ('Conceitos de física, química, biologia, etc.','1')
insert into Topico(nmtopico, temaid) values ('Geografia mundial','2')
insert into Topico(nmtopico, temaid) values ('História global','2')
insert into Topico(nmtopico, temaid) values ('Curiosidades diversas','2')
insert into Topico(nmtopico, temaid) values ('Filmes e séries','3')
insert into Topico(nmtopico, temaid) values ('Música e artistas','3')
insert into Topico(nmtopico, temaid) values ('Livros e autores','3')
insert into Topico(nmtopico, temaid) values ('Times e atletas','4')
insert into Topico(nmtopico, temaid) values ('Regras de diferentes esportes','4')
insert into Topico(nmtopico, temaid) values ('Recordes esportivos','4')
insert into Topico(nmtopico, temaid) values ('Grandes obras literárias','5')
insert into Topico(nmtopico, temaid) values ('Pintores e movimentos artísticos','5')
insert into Topico(nmtopico, temaid) values ('Autores clássicos e contemporâneos','5')
insert into Topico(nmtopico, temaid) values ('Eventos recentes no mundo','6')
insert into Topico(nmtopico, temaid) values ('Política internacional','6')
insert into Topico(nmtopico, temaid) values ('Questões socioeconômicas','6')
insert into Topico(nmtopico, temaid) values ('Culinária internacional','7')
insert into Topico(nmtopico, temaid) values ('Ingredientes e pratos típicos','7')
insert into Topico(nmtopico, temaid) values ('História da gastronomia','7')
insert into Topico(nmtopico, temaid) values ('Ecossistemas e biodiversidade','8')
insert into Topico(nmtopico, temaid) values ('Questões ambientais globais','8')
insert into Topico(nmtopico, temaid) values ('Energias renovavéis','8')
insert into Topico(nmtopico, temaid) values ('Palavras e frases em diferentes idiomas','9')
insert into Topico(nmtopico, temaid) values ('Tradições culturais','9')
insert into Topico(nmtopico, temaid) values ('Festividade ao redor do mundo','9')
insert into Topico(nmtopico, temaid) values ('Teorias psicológicas famosas','10')
insert into Topico(nmtopico, temaid) values ('Saúde mental e estratégias de bem-estar','10')
insert into Topico(nmtopico, temaid) values ('Personalidade e tipos de inteligência','10')

select*from Topico